// Traduzione delle sigle colore (dal foglio PIM) in nomi estesi in italiano.
// Se una sigla non e' in questa mappa, viene mostrata cosi' com'e'.
const Map<String, String> colorNames = {
  'AURORA GOLD': 'Oro Aurora',
  'AZ': 'Azzurro',
  'B': 'Nero',
  'BB': 'Blu Nero',
  'BK': 'Nero',
  'BL': 'Blu',
  'BLBK': 'Blu Nero',
  'BLU': 'Blu',
  'BR': 'Marrone',
  'CH': 'Champagne',
  'CRYSTAL BK': 'Nero Cristallo',
  'CY': 'Ciano',
  'GD': 'Oro',
  'GG': 'Grigio Ghiaccio',
  'GN': 'Verde',
  'GO': 'Oro',
  'GR': 'Verde',
  'GY': 'Grigio',
  'LA': 'Lavanda',
  'LAV': 'Lavanda',
  'LI': 'Verde Lime',
  'MI': 'Menta',
  'NA': 'Blu Navy',
  'OL': 'Verde Oliva',
  'OR': 'Arancione',
  'PK': 'Rosa',
  'PNK': 'Rosa',
  'PU': 'Viola',
  'PUR': 'Viola',
  'PURPLE': 'Viola',
  'RD': 'Rosso',
  'SAPPHIRE BK': 'Nero Zaffiro',
  'SB': 'Nero Siderale',
  'SG': 'Grigio Siderale',
  'SH': 'Grigio Scuro',
  'SL': 'Argento',
  'SLV': 'Argento',
  'SPG': 'Grigio Siderale',
  'STBK': 'Nero Stellato',
  'SV': 'Argento',
  'TBK': 'Nero Titanio',
  'TG': 'Verde Turchese',
  'VI': 'Violetto',
  'WA': 'Ambra',
  'WH': 'Bianco',
  'WHT': 'Bianco',
  'YE': 'Giallo',
  'YLW': 'Giallo',
};

String colorDisplayName(String code) {
  return colorNames[code.toUpperCase()] ?? code;
}
