// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2cpmRTASD-B01dQB76wR7KYgSlpr-t8',
    appId: '1:25265634572:web:5a866d864764076d26dd29',
    messagingSenderId: '25265634572',
    projectId: 'mwinventory-59853',
    authDomain: 'mwinventory-59853.firebaseapp.com',
    storageBucket: 'mwinventory-59853.firebasestorage.app',
    measurementId: 'G-QEWR0DZNR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqI-vV3Ulv_dUYW4_MbE7V_RGbTKY0f4',
    appId: '1:25265634572:android:620a0121f902734e26dd29',
    messagingSenderId: '25265634572',
    projectId: 'mwinventory-59853',
    storageBucket: 'mwinventory-59853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4EASovsJzQW9MexcycnY61jos3Cu4eYI',
    appId: '1:25265634572:ios:ffa4b52aa4af292b26dd29',
    messagingSenderId: '25265634572',
    projectId: 'mwinventory-59853',
    storageBucket: 'mwinventory-59853.firebasestorage.app',
    iosBundleId: 'com.example.mwinventory',
  );
}
