import 'product.dart';

// Catalogo PC: codici forniti (2026-08-16) + integrazione dal sito
// MediaWorld per i modelli venduti direttamente ma mancanti dall'elenco originale.
final List<Product> pcCatalog = [
  // --- MICROSOFT ---
  Product(
    id: 'pc1',
    name: 'Surface Pro Copilot+ PC',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfaceprocopilotpc.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '406553', storage: '512GB', screen: '13"'),
      PcVariant(code: '406539', storage: '256GB', screen: '13"'),
      PcVariant(
          code: '406550',
          cpu: 'Qualcomm Snapdragon X Plus X1P-64-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Sapphire'),
      PcVariant(
          code: '406554',
          cpu: 'Qualcomm Snapdragon X Elite X1E-80-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Black'),
      PcVariant(
          code: '406559',
          cpu: 'Qualcomm Snapdragon X Elite X1E-80-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Dune'),
    ],
  ),
  Product(
    id: 'pc2',
    name: 'Surface Pro 12',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfacepro12.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '424084', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc3',
    name: 'Surface Laptop 13',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfacelaptop13.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '595473', cpu: 'C8', ram: '8GB', storage: '256GB'),
      PcVariant(code: '424120', storage: '256GB'),
      PcVariant(
          code: '424131',
          cpu: 'Qualcomm Snapdragon X Plus',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Platinum'),
      PcVariant(
          code: '424135',
          cpu: 'Qualcomm Snapdragon X Plus',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Ocean'),
    ],
  ),
  Product(
    id: 'pc4',
    name: 'Surface Laptop Copilot+ PC',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfacelaptopcopilotpc.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '365569', storage: '512GB', screen: '13"'),
      PcVariant(
          code: '365570',
          cpu: 'Qualcomm Snapdragon X Elite X1E-80-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13.8"',
          color: 'Platinum'),
      PcVariant(
          code: '365571',
          cpu: 'Qualcomm Snapdragon X Elite X1E-80-100',
          ram: '16GB',
          storage: '256GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '15"',
          color: 'Platinum'),
    ],
  ),
  Product(
    id: 'pc5',
    name: 'Surface Pro 13',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfacepro13.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '584683', storage: '256GB'),
      PcVariant(
          code: '584693',
          cpu: 'Qualcomm Snapdragon X2 Plus X2P-64-100',
          ram: '24GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Black'),
      PcVariant(
          code: '584697',
          cpu: 'Qualcomm Snapdragon X2 Elite X2E-78-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13"',
          color: 'Platinum'),
    ],
  ),
  Product(
    id: 'pc6',
    name: 'Bundle Surface Pro 13 con tastiera',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftbundlesurfacepro13contastiera.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '584699', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc8',
    name: 'Surface Laptop 13,8',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfacelaptop138.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '584702',
          cpu: 'Qualcomm Snapdragon X2 Plus X2P-64-100',
          ram: '24GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13.8"',
          color: 'Platinum'),
      PcVariant(
          code: '584703',
          cpu: 'Qualcomm Snapdragon X2 Elite X2E-78-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '13.8"',
          color: 'Platinum'),
    ],
  ),
  Product(
    id: 'pc9',
    name: 'Surface Laptop 15',
    brand: 'Microsoft',
    category: 'PC',
    imagePath: 'assets/products/microsoftsurfacelaptop15.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '584704',
          cpu: 'Qualcomm Snapdragon X2 Plus X2P-64-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '15"',
          color: 'Platinum'),
      PcVariant(
          code: '584705',
          cpu: 'Qualcomm Snapdragon X2 Elite X2E-78-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '15"',
          color: 'Platinum'),
    ],
  ),
  // --- LG ---
  Product(
    id: 'pc10',
    name: 'gram 15U50U',
    brand: 'LG',
    category: 'PC',
    imagePath: 'assets/products/lggram15u50u.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '587776', cpu: 'U5', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc11',
    name: 'Gram 17Z90RU-G',
    brand: 'LG',
    category: 'PC',
    imagePath: 'assets/products/lggram17z90rug.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '556104', cpu: 'I5', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc12',
    name: 'gram 17Z90TL',
    brand: 'LG',
    category: 'PC',
    imagePath: 'assets/products/lggram17z90tl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '587777',
          cpu: 'Intel® Core Ultra 7 256V',
          ram: '16GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ GPU',
          screen: '17"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc13',
    name: 'gram 17Z90UB',
    brand: 'LG',
    category: 'PC',
    imagePath: 'assets/products/lggram17z90ub.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589079',
          cpu: 'Intel® Core Ultra 7 355',
          ram: '16GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ GPU',
          screen: '17"',
          color: 'Brown'),
    ],
  ),
  Product(
    id: 'pc14',
    name: 'gram 16ZB90S',
    brand: 'LG',
    category: 'PC',
    imagePath: 'assets/products/lggram16zb90s.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589137',
          cpu: 'Intel® Core Ultra 5 Intel Core Ultra 5 115U',
          storage: '512GB',
          screen: '16"',
          color: 'Black'),
    ],
  ),
  // --- MSI ---
  Product(
    id: 'pc15',
    name: 'Modern 15 F1MG-691IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msimodern15f1mg691it.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '527289', cpu: 'C7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc16',
    name: 'Cyborg 15 B2RWEKG-082IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msicyborg15b2rwekg082it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '451679',
          cpu: 'U7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5050 (8GB)'),
    ],
  ),
  Product(
    id: 'pc17',
    name: 'Modern 15 H AI C2HM-269IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msimodern15haic2hm269it.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '527243', cpu: 'U9', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc18',
    name: 'Katana 15 HX B14WFK-036IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msikatana15hxb14wfk036it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '432936',
          cpu: 'I7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060'),
    ],
  ),
  Product(
    id: 'pc19',
    name: 'Cyborg 15 B2RWFKG-632IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msicyborg15b2rwfkg632it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '551005',
          cpu: 'C7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc20',
    name: 'Prestige A16 AI+ A3-210IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msiprestigea16aia3210it.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '527157', cpu: 'RYZ9', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc21',
    name: 'Raider 18 AI A2XWIG-229IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msiraider18aia2xwig229it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '422104',
          cpu: 'Intel® Core Ultra 9 285HX',
          ram: '64GB',
          storage: '4TB',
          gpu: 'NVIDIA GeForce RTX™ 5080',
          screen: '18"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc22',
    name: 'Raider 18 AI A2XWJG-228IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msiraider18aia2xwjg228it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '422204',
          cpu: 'Intel® Core Ultra 9 285HX',
          ram: '64GB',
          storage: '4TB',
          gpu: 'NVIDIA GeForce RTX™ 5090',
          screen: '18"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc23',
    name: 'Vector 16 AI A2XWHG-200IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msivector16aia2xwhg200it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '422225',
          cpu: 'Intel® Core Ultra 7 255HX',
          ram: '32GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5070 Ti',
          screen: '16"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc24',
    name: 'Katana 17 HX B14WGK-044IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msikatana17hxb14wgk044it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '432252',
          cpu: 'Intel® Core I7 14650HX',
          ram: '16GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5070',
          screen: '17.3"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc25',
    name: 'Pulse A17 AI+ C3FKG-009IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msipulsea17aic3fkg009it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '432861',
          cpu: 'AMD Ryzen AI 7 350',
          ram: '16GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5060',
          screen: '17"',
          color: 'Nero siderale'),
    ],
  ),
  Product(
    id: 'pc26',
    name: 'Vector 18 AI A2XWJG-851IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msivector18aia2xwjg851it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '456416',
          cpu: 'Intel® Core Ultra 9 275HX',
          ram: '32GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5090',
          screen: '18"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc27',
    name: 'Prestige 13 Ukiyoe-217IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msiprestige13ukiyoe217it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '527176',
          cpu: 'Intel® Core Ultra 7 258V',
          ram: '32GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ 140V',
          screen: '13"',
          color: 'Nero siderale'),
    ],
  ),
  Product(
    id: 'pc28',
    name: 'VenturePro 15 A2REG-240IT',
    brand: 'MSI',
    category: 'PC',
    imagePath: 'assets/products/msiventurepro15a2reg240it.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '527397',
          cpu: 'Intel® Core 7 240H',
          ram: '16GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5050',
          screen: '15.6"',
          color: 'Grey'),
    ],
  ),
  // --- ASUS ---
  Product(
    id: 'pc29',
    name: 'CX3402CVA-PQ0669',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuscx3402cvapq0669.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '425413', cpu: 'I3', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc30',
    name: 'Chromebook CX3402',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuschromebookcx3402.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '574650', cpu: 'C3', ram: '8GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc31',
    name: 'Vivobook 15 F1504',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusvivobook15f1504.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '425638', cpu: 'C5', ram: '16GB', storage: '512GB'),
      PcVariant(code: '558231', cpu: 'C5', ram: '16GB', storage: '512GB'),
      PcVariant(code: '499342', cpu: 'C7', ram: '16GB', storage: '512GB'),
      PcVariant(code: '558230', cpu: 'C7', ram: '16GB', storage: '1TB'),
      PcVariant(
          code: '416311',
          cpu: 'Intel® Core I3 1315U',
          ram: '8GB',
          storage: '512GB',
          gpu: 'Intel® UHD Graphics',
          screen: '15.6"',
          color: 'Blue'),
    ],
  ),
  Product(
    id: 'pc32',
    name: 'F1504VA-BQ131W',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusf1504vabq131w.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '425640', cpu: 'I7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc33',
    name: 'Vivobook 15 M1502',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusvivobook15m1502.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '506162', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc34',
    name: 'Vivobook 16 F1605',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusvivobook16f1605.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '449372', cpu: 'I7', ram: '16GB', storage: '1TB'),
      PcVariant(code: '558509', cpu: 'C9', ram: '24GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc35',
    name: 'Vivobook 16 F1607',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusvivobook16f1607.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '558307', cpu: 'U7', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc36',
    name: 'Vivobook S14 S3407',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusvivobooks14s3407.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '558493', cpu: 'SQX1', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc37',
    name: 'Vivobook S14 S5406',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusvivobooks14s5406.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '575268', cpu: 'U5', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc38',
    name: 'Zenbook 14 UM3406',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuszenbook14um3406.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '558305', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc39',
    name: 'Zenbook 14 UX3405',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuszenbook14ux3405.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '558580', cpu: 'U9', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc40',
    name: 'V16 V3607',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusv16v3607.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '450497',
          cpu: 'C7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc41',
    name: 'TUF Gaming A16 FA608',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asustufgaminga16fa608.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '425641',
          cpu: 'RYZ7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
      PcVariant(
          code: '506172',
          cpu: 'RYZ7',
          ram: '32GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
      PcVariant(
          code: '575998',
          cpu: 'RYZ7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
      PcVariant(
          code: '575986',
          cpu: 'AMD Ryzen 9 8940HX',
          ram: '16GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5070',
          screen: '16"',
          color: 'Grey'),
      PcVariant(
          code: '576012',
          cpu: 'AMD Ryzen 7 260',
          ram: '16GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5050',
          screen: '16"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc42',
    name: 'G614PP-RV021W',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusg614pprv021w.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '426515',
          cpu: 'RYZ9',
          ram: '32GB',
          storage: '1TB',
          gpu: 'RTX 5070 (8GB)'),
    ],
  ),
  Product(
    id: 'pc43',
    name: 'ROG Strix Scar G16 G635',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusrogstrixscarg16g635.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '427539',
          cpu: 'Intel® Core Ultra 9 275HX',
          ram: '32GB',
          storage: '2TB',
          gpu: 'NVIDIA GeForce RTX™ 5080',
          screen: '16"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc44',
    name: 'ROG Strix G18 G815',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asusrogstrixg18g815.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '427545',
          cpu: 'Intel® Core Ultra 9 275HX',
          ram: '32GB',
          storage: '2TB',
          gpu: 'NVIDIA GeForce RTX™ 5080',
          screen: '18"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc45',
    name: 'Zenbook S 16 UM5606',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuszenbooks16um5606.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '558673',
          cpu: 'AMD Ryzen 9 465',
          ram: '32GB',
          storage: '1TB',
          gpu: 'AMD Radeon™ Onboard Graphics',
          screen: '16"',
          color: 'White'),
    ],
  ),
  Product(
    id: 'pc46',
    name: 'Zenbook A14 UX3407',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuszenbooka14ux3407.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '574678',
          cpu: 'Qualcomm Snapdragon X X1 26 100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '14"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc47',
    name: 'Chromebook CM1505',
    brand: 'Asus',
    category: 'PC',
    imagePath: 'assets/products/asuschromebookcm1505.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '575292',
          cpu: 'MediaTek Kompanio Kompanio 540',
          ram: '8GB',
          storage: '128GB',
          gpu: 'ARM Mali-G57',
          screen: '15.6"',
          color: 'Grey'),
    ],
  ),
  // --- ACER ---
  Product(
    id: 'pc48',
    name: 'Chromebook 314 CBOA314-1H',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerchromebook314cboa3141h.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '405802', cpu: 'N4500 CEL', ram: '4GB', storage: '64GB'),
      PcVariant(code: '547040', cpu: 'CEL', ram: '8GB', storage: '64GB'),
    ],
  ),
  Product(
    id: 'pc49',
    name: 'Aspire Lite 15 AL15-32P',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirelite15al1532p.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '432800', cpu: 'CEL', ram: '4GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc50',
    name: 'Aspire Lite 15 AL15-32P-C425',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirelite15al1532pc425.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '581132', cpu: 'CEL', ram: '4GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc51',
    name: 'Aspire Lite 15 AL15-46P',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirelite15al1546p.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '562197', cpu: 'RYZ3', ram: '8GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc52',
    name: 'Chromebook Plus 516',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerchromebookplus516.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '547044', cpu: 'I3', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc53',
    name: 'Aspire Lite 15 AL15-45P',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirelite15al1545p.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '562181', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc54',
    name: 'Aspire Go 15 AG15-42P',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirego15ag1542p.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '432801', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc55',
    name: 'Aspire 16 AI Laptop',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspire16ailaptop.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '546981', cpu: 'QX1', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc56',
    name: 'Aspire Lite 15 AL15-54P-56N1',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirelite15al1554p56n1.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '562806', cpu: 'U5', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc57',
    name: 'Aspire Go 15 AG15-72P',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirego15ag1572p.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '546923', cpu: 'C5', ram: '32GB', storage: '512GB'),
      PcVariant(code: '546950', cpu: 'C7', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc58',
    name: 'Aspire 15 A15-51M-93PU',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspire15a1551m93pu.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '546971', cpu: 'I9', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc59',
    name: 'Aspire Go 16 AG16-71P',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspirego16ag1671p.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '562127', cpu: 'I9', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc60',
    name: 'Swift Go 16 AI SFG16-74',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerswiftgo16aisfg1674.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '562118', cpu: 'U7', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc61',
    name: 'Nitro V 15 ANV15-52-92F1',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acernitrov15anv155292f1.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '496147',
          cpu: 'I9',
          ram: '32GB',
          storage: '1TB',
          gpu: 'RTX 5050 (8GB)'),
    ],
  ),
  Product(
    id: 'pc62',
    name: 'Nitro V 15 ANV15-52-97GL',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acernitrov15anv155297gl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '547399',
          cpu: 'I9',
          ram: '32GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc63',
    name: 'Nitro V 16S AI ANV16S-41',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acernitrov16saianv16s41.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '496153',
          cpu: 'RYZ7',
          ram: '32GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc64',
    name: 'Predator Helios 18 AI',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerpredatorhelios18ai.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '454707',
          cpu: 'Intel® Core Ultra 9 275HX',
          ram: '32GB',
          storage: '2TB',
          gpu: 'NVIDIA GeForce RTX™ 5080',
          screen: '18"',
          color: 'Black'),
      PcVariant(
          code: '548099',
          cpu: 'Intel® Core Ultra 9 275HX',
          ram: '64GB',
          storage: '3TB',
          gpu: 'NVIDIA GeForce RTX™ 5090',
          screen: '18"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc65',
    name: 'Nitro V 17 AI ANV17-41',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acernitrov17aianv1741.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '496166',
          cpu: 'AMD Ryzen 7 260',
          ram: '32GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5060',
          screen: '17.3"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc66',
    name: 'Aspire 14 AI Copilot+ PC',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspire14aicopilotpc.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '547029',
          cpu: 'Intel® Core Ultra 7 256V',
          ram: '16GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ GPU',
          screen: '14"',
          color: 'Silver'),
    ],
  ),
  Product(
    id: 'pc67',
    name: 'Predator Helios 16 AI',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerpredatorhelios16ai.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '548087',
          cpu: 'Intel® Core Ultra 9 275HX',
          ram: '32GB',
          storage: '2TB',
          gpu: 'NVIDIA GeForce RTX™ 5090',
          screen: '16"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc68',
    name: 'Aspire 16 AI A16-61M',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/aceraspire16aia1661m.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '562161',
          cpu: 'AMD Ryzen AI 5 330',
          ram: '16GB',
          storage: '512GB',
          gpu: 'AMD Radeon™ Onboard Graphics',
          screen: '16"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc69',
    name: 'Nitro V 16 AI ANV16-42',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acernitrov16aianv1642.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '562215',
          cpu: 'AMD Ryzen 7 260',
          ram: '32GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5070',
          screen: '16"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc70',
    name: 'Predator Triton 14 AI',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerpredatortriton14ai.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '562236',
          cpu: 'Intel® Core Ultra 9 288V',
          ram: '32GB',
          storage: '2TB',
          gpu: 'NVIDIA GeForce RTX™ 5070',
          screen: '14.5"',
          color: 'Black'),
    ],
  ),
  Product(
    id: 'pc71',
    name: 'Chromebook TAB 311 CW311-3HN-K8W8',
    brand: 'Acer',
    category: 'PC',
    imagePath: 'assets/products/acerchromebooktab311cw3113hnk8w8.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589444',
          cpu: 'MediaTek MTK MT8186',
          ram: '4GB',
          storage: '64GB',
          gpu: 'ARM Mali-G52',
          screen: '11"',
          color: 'Silver'),
    ],
  ),
  // --- LENOVO ---
  Product(
    id: 'pc72',
    name: 'Chromebook IP Slim3',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovochromebookipslim3.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '361695', cpu: 'KOMP520', ram: '8GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc73',
    name: 'Chrome 14M8911',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovochrome14m8911.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '588612', cpu: 'MKT', ram: '8GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc74',
    name: 'IPS Slim 3 Chrome PLUS',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoipsslim3chromeplus.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '408733', cpu: 'I3-N305', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc75',
    name: 'IdeaPad Slim 3 82XQ004GIX',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim382xq004gix.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '218856', cpu: 'RYZ3', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc76',
    name: 'IdeaPad Slim 3',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim3.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '531761', cpu: 'RYZ5', ram: '16GB', storage: '512GB'),
      PcVariant(code: '589624', cpu: 'RYZ5', ram: '8GB', storage: '512GB'),
      PcVariant(code: '588151', cpu: 'RYZ5', ram: '16GB', storage: '512GB'),
      PcVariant(code: '408735', cpu: 'I7', ram: '16GB', storage: '512GB'),
      PcVariant(code: '588127', cpu: 'QX1', ram: '16GB', storage: '512GB'),
      PcVariant(code: '583088', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc77',
    name: 'IdeaPad Slim 3 83L70047IX',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim383l70047ix.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '583648', cpu: 'C3', ram: '8GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc78',
    name: 'IdeaPad Flex 5 14ABR8',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadflex514abr8.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '432526', cpu: 'RYZ5', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc79',
    name: 'IdeaPad Slim 3 15IAH8',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim315iah8.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '420671', cpu: 'I5', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc80',
    name: 'IdeaPad Slim 3 83RR00JUIX',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim383rr00juix.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '596502', cpu: 'C5', ram: '8GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc81',
    name: 'IdeaPad Slim 3 15IRH10R',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim315irh10r.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '434727', cpu: 'C7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc82',
    name: 'IdeaPad Slim 5',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim5.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '586904', cpu: 'U5', ram: '16GB', storage: '512GB'),
      PcVariant(code: '498085', cpu: 'C7', ram: '12GB', storage: '1TB'),
      PcVariant(code: '586594', cpu: 'U9', ram: '16GB', storage: '512GB'),
      PcVariant(
          code: '564600',
          cpu: 'Intel® Core Ultra 9 185H',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Intel®',
          screen: '16"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc83',
    name: 'IdeaPad Flex 5',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadflex5.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589941', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc84',
    name: 'IdeaPad Slim 3i',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoideapadslim3i.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '596500', cpu: 'C7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc85',
    name: 'Yoga Slim 7i Aura Edition',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoyogaslim7iauraedition.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '564621', cpu: 'U7', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc86',
    name: 'LOQ',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoloq.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '596064',
          cpu: 'RYZ7',
          ram: '16GB',
          storage: '512GB',
          gpu: 'RTX 4050 (6GB)'),
    ],
  ),
  Product(
    id: 'pc87',
    name: 'LOQ 15IRX10',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoloq15irx10.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '450618',
          cpu: 'I7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
      PcVariant(
          code: '588837',
          cpu: 'I7',
          ram: '16GB',
          storage: '512GB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc88',
    name: 'LOQ Essential',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoloqessential.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '596052',
          cpu: 'I7',
          ram: '16GB',
          storage: '512GB',
          gpu: 'RTX 5050 (8GB)'),
    ],
  ),
  Product(
    id: 'pc89',
    name: 'LOQ 15',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoloq15.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '564616',
          cpu: 'Intel® Core I7 13650HX',
          ram: '32GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5070',
          screen: '15.6"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc90',
    name: 'Chromebook Duet',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovochromebookduet.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '588667',
          cpu: 'MediaTek Kompanio 838',
          ram: '8GB',
          storage: '128GB',
          gpu: 'ARM Mali-G57',
          screen: '10.95"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc91',
    name: 'Yoga Slim 7 Ultra',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoyogaslim7ultra.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589953',
          cpu: 'Intel® Core Ultra 7 355',
          ram: '32GB',
          storage: '1TB',
          gpu: 'Intel®',
          screen: '14"',
          color: 'Blue'),
    ],
  ),
  Product(
    id: 'pc92',
    name: 'Yoga Book 9',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovoyogabook9.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '590043',
          cpu: 'Intel® Core Ultra 7 255H',
          ram: '32GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ GPU',
          screen: '14"',
          color: 'Blue'),
    ],
  ),
  Product(
    id: 'pc93',
    name: 'Legion 5 15IAX10',
    brand: 'Lenovo',
    category: 'PC',
    imagePath: 'assets/products/lenovolegion515iax10.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '594436',
          cpu: 'Intel® Core Ultra 7 255HX',
          ram: '16GB',
          storage: '1TB',
          gpu: 'NVIDIA GeForce RTX™ 5060',
          screen: '15.1"',
          color: 'Black'),
    ],
  ),
  // --- HP ---
  Product(
    id: 'pc94',
    name: 'Chromebook 14a-NF0004NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpchromebook14anf0004nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '579894', cpu: 'N100', ram: '4GB', storage: '128GB'),
    ],
  ),
  Product(
    id: 'pc95',
    name: '15-fc0111nl',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fc0111nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '563057', cpu: 'RYZ3', ram: '8GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc96',
    name: 'Chromebook Plus 14a',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpchromebookplus14a.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '379540', cpu: 'I3-N305', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc97',
    name: '15-FD0119NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd0119nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '531732', cpu: 'I3', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc98',
    name: '17-CP2001NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp17cp2001nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '575754', cpu: 'RYZ3', ram: '8GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc99',
    name: '15-FD0103NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd0103nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '497964', cpu: 'I5', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc100',
    name: 'Chromebook 14a-NF0002NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpchromebook14anf0002nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '580007', cpu: 'I3', ram: '8GB', storage: '256GB'),
    ],
  ),
  Product(
    id: 'pc101',
    name: '15-fc1005nl',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fc1005nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '579359', cpu: 'RYZ5', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc102',
    name: '15-FD0121NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd0121nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '531742', cpu: 'I5', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc103',
    name: '15-fc0095nl',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fc0095nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '546144', cpu: 'RYZ7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc104',
    name: '15-FD0129NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd0129nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '563666', cpu: 'C5', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc105',
    name: 'OmniBook 3 15-FN0007NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook315fn0007nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '548551', cpu: 'RYZ5', ram: '24GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc106',
    name: '15-FC0108NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fc0108nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '563301', cpu: 'RYZ7', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc107',
    name: '15-FD2003NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd2003nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589111', cpu: 'U5', ram: '8GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc108',
    name: '15-fc0121nl',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fc0121nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '579363', cpu: 'RYZ7', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc109',
    name: 'OmniBook 5 14-FP0010NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook514fp0010nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '548623', cpu: 'C5', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc110',
    name: '15-FD1008NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd1008nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589120', cpu: 'C5', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc111',
    name: 'OmniBook 5 Flip 2-in-1 14-FP0005NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5flip2in114fp0005nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589130', cpu: 'C5', ram: '8GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc112',
    name: 'OmniBook 3 16-by0008nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook316by0008nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589627', cpu: 'RYZ7', ram: '8GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc113',
    name: 'OmniBook 5 16-AF1027NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook516af1027nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '548586', cpu: 'U7', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc114',
    name: '15-fd1007nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hp15fd1007nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589644', cpu: 'C7', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc115',
    name: 'OmniBook 5 NGAI 16-BF0001NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ngai16bf0001nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '589487', cpu: 'QX1', ram: '16GB', storage: '512GB'),
    ],
  ),
  Product(
    id: 'pc116',
    name: 'OmniBook 5 AI 16-AF1033NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ai16af1033nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '563663', cpu: 'U7', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc117',
    name: 'OmniBook 7 AI 14-FR0019NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook7ai14fr0019nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '546046', cpu: 'U7', ram: '16GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc118',
    name: 'OmniBook 5 AI 16-AF1034NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ai16af1034nl.png',
    variants: [],
    pcVariants: [
      PcVariant(code: '579621', cpu: 'U7', ram: '32GB', storage: '1TB'),
    ],
  ),
  Product(
    id: 'pc119',
    name: 'Victus Gaming 15-fa2002nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpvictusgaming15fa2002nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589887',
          cpu: 'I5',
          ram: '16GB',
          storage: '512GB',
          gpu: 'RTX 3050 (6GB)'),
    ],
  ),
  Product(
    id: 'pc120',
    name: 'OMEN 14-FB1002NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomen14fb1002nl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '497827',
          cpu: 'U7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc121',
    name: 'Victus 15-FB3004NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpvictus15fb3004nl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '548762',
          cpu: 'RYZ7',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc122',
    name: 'HyperX OMEN Gaming 15-gb0013nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hphyperxomengaming15gb0013nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589860',
          cpu: 'RYZ9',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5060 (8GB)'),
    ],
  ),
  Product(
    id: 'pc123',
    name: 'HyperX OMEN Gaming 16-AP1000NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hphyperxomengaming16ap1000nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589488',
          cpu: 'RYZ9',
          ram: '16GB',
          storage: '1TB',
          gpu: 'RTX 5070 (8GB)'),
    ],
  ),
  Product(
    id: 'pc124',
    name: 'OMNIBOOK FLIP 14-FH0019NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibookflip14fh0019nl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '546711',
          cpu: 'Intel® Core Ultra 7 258V',
          ram: '32GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ GPU',
          screen: '14"',
          color: 'Blue'),
    ],
  ),
  Product(
    id: 'pc125',
    name: 'OMNIBOOK FLIP 14-FH0020NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibookflip14fh0020nl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '548576',
          cpu: 'Intel® Core Ultra 7 256V',
          ram: '16GB',
          storage: '1TB',
          gpu: 'Intel® Arc™ GPU',
          screen: '14"',
          color: 'Blue'),
    ],
  ),
  Product(
    id: 'pc126',
    name: 'OMNIBOOK 5 NGAI 16-AG1025NL',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ngai16ag1025nl.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '579606',
          cpu: 'AMD Ryzen AI 7 350',
          ram: '16GB',
          storage: '1TB',
          gpu: 'AMD',
          screen: '16"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc127',
    name: 'CHROMEBOOK X360 14B-CD0001NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpchromebookx36014bcd0001nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '580016',
          cpu: 'Intel® N100 N100',
          ram: '4GB',
          storage: '128GB',
          gpu: 'Intel® UHD Graphics',
          screen: '14"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc128',
    name: 'CHROMEBOOK 14A-NF0013NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpchromebook14anf0013nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '587804',
          cpu: 'Intel® N100 N100',
          ram: '8GB',
          gpu: 'Intel® UHD Graphics',
          screen: '14"',
          color: 'Silver'),
    ],
  ),
  Product(
    id: 'pc129',
    name: 'OMNIBOOK 5 AI 16-AF1009NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ai16af1009nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '587817',
          cpu: 'Intel® Core Ultra 7 255U',
          ram: '16GB',
          storage: '1TB',
          gpu: 'Intel®',
          screen: '16"',
          color: 'Silver'),
    ],
  ),
  Product(
    id: 'pc130',
    name: 'OMNIBOOK 5 FLIP 2-IN-1 14-FP0004NLX',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5flip2in114fp0004nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589132',
          cpu: 'Intel® Core 5 120U',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Intel®',
          screen: '14"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc131',
    name: 'OmniBook 3 17-dp0000nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook317dp0000nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589666',
          cpu: 'AMD Ryzen 7 160',
          ram: '8GB',
          storage: '512GB',
          gpu: 'AMD Radeon™ Onboard Graphics',
          screen: '17.3"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc132',
    name: 'OmniBook 5 NGI 16-bp0014nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ngi16bp0014nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589678',
          cpu: 'AMD Ryzen AI 7 445',
          ram: '16GB',
          storage: '1TB',
          gpu: 'AMD',
          screen: '16"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc133',
    name: 'OmniBook 5 NGAI 16-bp0015nlx',
    brand: 'HP',
    category: 'PC',
    imagePath: 'assets/products/hpomnibook5ngai16bp0015nlx.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '589790',
          cpu: 'AMD Ryzen AI 5 330',
          ram: '16GB',
          storage: '512GB',
          gpu: 'AMD Radeon™ Onboard Graphics',
          screen: '16"',
          color: 'Argento'),
    ],
  ),
  // --- APPLE ---
  Product(
    id: 'pc201',
    name: 'Mac Mini',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacmini.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '187604',
          cpu: 'M4 Pro',
          ram: '24GB',
          storage: '512GB',
          gpu: '12-core CPU, 16-core GPU'),
      PcVariant(
          code: '187610',
          cpu: 'M4',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 10-core GPU'),
    ],
  ),
  Product(
    id: 'pc202',
    name: 'iMac 24\'\'',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/appleimac24.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '374603',
          cpu: 'M4',
          ram: '16GB',
          storage: '256GB',
          gpu: '8-core CPU, 8-core GPU',
          screen: '24"',
          color: 'Argento'),
      PcVariant(
          code: '374604',
          cpu: 'M4',
          ram: '16GB',
          storage: '256GB',
          gpu: '8-core CPU, 8-core GPU',
          screen: '24"',
          color: 'Verde'),
      PcVariant(
          code: '374607',
          cpu: 'M4',
          ram: '16GB',
          storage: '256GB',
          gpu: '8-core CPU, 8-core GPU',
          screen: '24"',
          color: 'Blu'),
      PcVariant(
          code: '374609',
          cpu: 'M4',
          ram: '16GB',
          storage: '256GB',
          gpu: '8-core CPU, 8-core GPU',
          screen: '24"',
          color: 'Rosa'),
    ],
  ),
  Product(
    id: 'pc203',
    name: 'Mac Studio',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacstudio.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '424436',
          cpu: 'M4 Max',
          ram: '35GB',
          storage: '512GB',
          gpu: '14-core CPU, 32-core GPU'),
      PcVariant(
          code: '424437',
          cpu: 'M3 Ultra',
          ram: '96GB',
          storage: '1TB',
          gpu: '25-core CPU, 60-core GPU'),
    ],
  ),
  Product(
    id: 'pc204',
    name: 'MacBook Air 13\'\'',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacbookair13.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '424448',
          cpu: 'M4',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '13"',
          color: 'Mezzanotte'),
      PcVariant(
          code: '566907',
          cpu: 'M5',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 8-core GPU',
          screen: '13"',
          color: 'Argento'),
      PcVariant(
          code: '566908',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '13"',
          color: 'Argento'),
      PcVariant(
          code: '566911',
          cpu: 'M5',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 8-core GPU',
          screen: '13"',
          color: 'Galassia'),
      PcVariant(
          code: '566912',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '13"',
          color: 'Galassia'),
      PcVariant(
          code: '566914',
          cpu: 'M5',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 8-core GPU',
          screen: '13"',
          color: 'Mezzanotte'),
      PcVariant(
          code: '566915',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '13"',
          color: 'Mezzanotte'),
      PcVariant(
          code: '566918',
          cpu: 'M5',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 8-core GPU',
          screen: '13"',
          color: 'Celeste'),
      PcVariant(
          code: '566919',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '13"',
          color: 'Celeste'),
    ],
  ),
  Product(
    id: 'pc205',
    name: 'MacBook Pro 14\'\'',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacbookpro14.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '424454',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '14"',
          color: 'Nero Siderale'),
      PcVariant(
          code: '424456',
          cpu: 'M5',
          ram: '16GB',
          storage: '512GB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '14"',
          color: 'Argento'),
      PcVariant(
          code: '424457',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '14"',
          color: 'Argento'),
      PcVariant(
          code: '566974',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '1TB',
          gpu: '15-core CPU, 16-core GPU',
          screen: '14"',
          color: 'Nero Siderale'),
      PcVariant(
          code: '566975',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '2TB',
          gpu: '15-core CPU, 16-core GPU',
          screen: '14"',
          color: 'Nero Siderale'),
      PcVariant(
          code: '566977',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '2TB',
          gpu: '18-core CPU, 20-core GPU',
          screen: '14"',
          color: 'Nero Siderale'),
      PcVariant(
          code: '566981',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '1TB',
          gpu: '15-core CPU, 16-core GPU',
          screen: '14"',
          color: 'Argento'),
      PcVariant(
          code: '566982',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '2TB',
          gpu: '15-core CPU, 16-core GPU',
          screen: '14"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc206',
    name: 'MacBook Air 15\'\'',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacbookair15.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '424508',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '15"',
          color: 'Argento'),
      PcVariant(
          code: '424512',
          cpu: 'M5',
          ram: '24GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '15"',
          color: 'Galassia'),
      PcVariant(
          code: '424517',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '15"',
          color: 'Mezzanotte'),
      PcVariant(
          code: '424520',
          cpu: 'M5',
          ram: '16GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '15"',
          color: 'Celeste'),
      PcVariant(
          code: '424521',
          cpu: 'M5',
          ram: '24GB',
          storage: '1TB',
          gpu: '10-core CPU, 10-core GPU',
          screen: '15"',
          color: 'Celeste'),
    ],
  ),
  Product(
    id: 'pc207',
    name: 'iMac 24\'\' CTO con display Retina 4,5K',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/appleimac24ctocondisplayretina45k.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '566258',
          cpu: 'M4',
          ram: '16GB',
          storage: '256GB',
          gpu: '8-core CPU, 8-core GPU',
          screen: '24"',
          color: 'Argento con Gigabit Ethernet'),
      PcVariant(
          code: '582906',
          cpu: 'M4',
          ram: '16GB',
          storage: '256GB',
          gpu: '8-core CPU, 8-core GPU',
          screen: '24"',
          color: 'Blu con Gigabit Ethernet'),
    ],
  ),
  Product(
    id: 'pc208',
    name: 'MacBook Pro 16\'\'',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacbookpro16.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '566746',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '1TB',
          gpu: '18-core CPU, 20-core GPU',
          screen: '16"',
          color: 'Nero Siderale'),
      PcVariant(
          code: '566747',
          cpu: 'M5 Pro',
          ram: '48GB',
          storage: '1TB',
          gpu: '18-core CPU, 20-core GPU',
          screen: '16"',
          color: 'Nero Siderale'),
      PcVariant(
          code: '566750',
          cpu: 'M5 Pro',
          ram: '24GB',
          storage: '1TB',
          gpu: '18-core CPU, 20-core GPU',
          screen: '16"',
          color: 'Argento'),
    ],
  ),
  Product(
    id: 'pc209',
    name: 'MacBook Neo 13\'\'',
    brand: 'Apple',
    category: 'PC',
    imagePath: 'assets/products/applemacbookneo13.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '566922',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '512GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Argento'),
      PcVariant(
          code: '566923',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '256GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Giallo agrume'),
      PcVariant(
          code: '566924',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '512GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Giallo agrume'),
      PcVariant(
          code: '566925',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '256GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Indaco'),
      PcVariant(
          code: '566926',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '512GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Indaco'),
      PcVariant(
          code: '566927',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '256GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Rosa pastello'),
      PcVariant(
          code: '566928',
          cpu: 'A18 Pro',
          ram: '8GB',
          storage: '512GB',
          gpu: '6-core CPU, 5-core GPU',
          screen: '13"',
          color: 'Rosa pastello'),
    ],
  ),
  // --- SAMSUNG ---
  Product(
    id: 'pc301',
    name: 'Galaxy Book4',
    brand: 'Samsung',
    category: 'PC',
    imagePath: 'assets/products/samsunggalaxybook4.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '236411',
          cpu: 'Intel® Core 7 150U',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Intel® Iris® Xᵉ',
          screen: '15.6"',
          color: 'Grigio siderale'),
    ],
  ),
  Product(
    id: 'pc302',
    name: 'Galaxy Book4 Edge 14',
    brand: 'Samsung',
    category: 'PC',
    imagePath: 'assets/products/samsunggalaxybook4edge14.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '396390',
          cpu: 'Qualcomm Snapdragon X Elite X1E-80-100',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Qualcomm Adreno™ Onboard Graphics',
          screen: '14"',
          color: 'Sapphire'),
    ],
  ),
  Product(
    id: 'pc303',
    name: 'Galaxy Book6 Pro',
    brand: 'Samsung',
    category: 'PC',
    imagePath: 'assets/products/samsunggalaxybook6pro.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '564002',
          cpu: 'Intel® Core Ultra 7 356H',
          ram: '32GB',
          storage: '1TB',
          gpu: 'Intel® UHD Graphics',
          screen: '16"',
          color: 'Grey'),
      PcVariant(
          code: '564003',
          cpu: 'Intel® Core Ultra 7 356H',
          ram: '32GB',
          storage: '1TB',
          gpu: 'Intel® UHD Graphics',
          screen: '14"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc304',
    name: 'Galaxy Book6',
    brand: 'Samsung',
    category: 'PC',
    imagePath: 'assets/products/samsunggalaxybook6.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '564004',
          cpu: 'Intel® Core Ultra 7 355',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Intel® UHD Graphics',
          screen: '16"',
          color: 'Grey'),
      PcVariant(
          code: '564005',
          cpu: 'Intel® Core Ultra 7 355',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Intel® UHD Graphics',
          screen: '14"',
          color: 'Grey'),
    ],
  ),
  Product(
    id: 'pc305',
    name: 'Galaxy Book4 15.6 Core7',
    brand: 'Samsung',
    category: 'PC',
    imagePath: 'assets/products/samsunggalaxybook4156core7.png',
    variants: [],
    pcVariants: [
      PcVariant(
          code: '593566',
          cpu: 'Intel® Core 7 150U',
          ram: '16GB',
          storage: '512GB',
          gpu: 'Intel® Iris® Xᵉ',
          screen: '15.6"',
          color: 'Grey'),
    ],
  ),
];
