import 'product.dart';

// Catalogo Telefonia generato dai codici PIM forniti (2026-08-16).
// Le immagini non erano disponibili in fase di importazione: imagePath
// punta a un file convenzionale in assets/products/ da aggiungere in seguito;
// finche' manca, la UI mostra un'icona segnaposto (vedi errorBuilder).
final List<Product> telefoniaCatalog = [
  // --- APPLE ---
  Product(
    id: 't1',
    name: 'iPhone 16E',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/appleiphone16e.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '387748'),
      ProductVariant(storage: '128GB', color: 'WH', code: '387749'),
      ProductVariant(storage: '256GB', color: 'BK', code: '387750'),
      ProductVariant(storage: '512GB', color: 'Nero', code: '387752'),
    ],
  ),
  Product(
    id: 't2',
    name: 'iPhone 15',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/iphone15.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BL', code: '187824'),
      ProductVariant(storage: '128GB', color: 'Nero', code: '187821'),
      ProductVariant(storage: '256GB', color: 'BK', code: '187828'),
      ProductVariant(storage: '256GB', color: 'BL', code: '187836'),
    ],
  ),
  Product(
    id: 't3',
    name: 'iPhone 17e',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/appleiphone17e.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'WH', code: '394756'),
      ProductVariant(storage: '256GB', color: 'Nero', code: '394755'),
    ],
  ),
  Product(
    id: 't4',
    name: 'iPhone 16',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/iphone16.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '387644'),
      ProductVariant(storage: '128GB', color: 'WH', code: '387651'),
      ProductVariant(storage: '128GB', color: 'BL', code: '387654'),
      ProductVariant(storage: '128GB', color: 'GN', code: '387655'),
      ProductVariant(storage: '128GB', color: 'Rosa', code: '387652'),
    ],
  ),
  Product(
    id: 't5',
    name: 'iPhone 16 Plus',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/appleiphone16plus.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '387683'),
      ProductVariant(storage: '128GB', color: 'BL', code: '387686'),
      ProductVariant(storage: '128GB', color: 'Verde Acqua', code: '387688'),
      ProductVariant(storage: '256GB', color: 'BK', code: '387696'),
      ProductVariant(storage: '256GB', color: 'Bianco', code: '387697'),
      ProductVariant(storage: '256GB', color: 'Blu Oltremare', code: '387699'),
      ProductVariant(storage: '256GB', color: 'Verde Acqua', code: '387700'),
    ],
  ),
  Product(
    id: 't6',
    name: 'iPhone 17',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/iphone17.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '389194'),
      ProductVariant(storage: '256GB', color: 'WH', code: '389195'),
      ProductVariant(storage: '256GB', color: 'LAV', code: '389198'),
      ProductVariant(storage: '256GB', color: 'GN', code: '389199'),
      ProductVariant(storage: '256GB', color: 'AZ', code: '389196'),
      ProductVariant(storage: '512GB', color: 'Bianco', code: '389227'),
      ProductVariant(storage: '512GB', color: 'Lavanda', code: '390974'),
      ProductVariant(storage: '512GB', color: 'Salvia', code: '391203'),
    ],
  ),
  Product(
    id: 't7',
    name: 'iPhone 17 (SMART)',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/appleiphone17smart.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '529407'),
    ],
  ),
  Product(
    id: 't8',
    name: 'iPhone Air',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/appleiphoneair.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'GD', code: '393509'),
      ProductVariant(storage: '256GB', color: 'BL', code: '394703'),
      ProductVariant(storage: '1TB', color: 'WH', code: '394730'),
      ProductVariant(storage: '1TB', color: 'GD', code: '394733'),
      ProductVariant(storage: '512GB', color: 'BL', code: '394707'),
      ProductVariant(storage: '512GB', color: 'Oro Chiaro', code: '394706'),
      ProductVariant(storage: '1TB', color: 'Nero Siderale', code: '394729'),
      ProductVariant(storage: '1TB', color: 'Celeste', code: '394734'),
    ],
  ),
  Product(
    id: 't9',
    name: 'iPhone Air (SMART)',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/appleiphoneairsmart.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BL', code: '529541'),
    ],
  ),
  Product(
    id: 't10',
    name: 'iPhone 17 Pro',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/iphone17pro.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'SL', code: '391204'),
      ProductVariant(storage: '256GB', color: 'OR', code: '391205'),
      ProductVariant(storage: '256GB', color: 'BL', code: '391206'),
      ProductVariant(storage: '512GB', color: 'SL', code: '391500'),
      ProductVariant(storage: '512GB', color: 'OR', code: '391501'),
      ProductVariant(storage: '512GB', color: 'BL', code: '391502'),
    ],
  ),
  Product(
    id: 't11',
    name: 'iPhone 17 Pro Max',
    brand: 'Apple',
    category: 'Telefonia',
    imagePath: 'assets/products/iphone17promax.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'SL', code: '391513'),
      ProductVariant(storage: '256GB', color: 'OR', code: '391672'),
      ProductVariant(storage: '256GB', color: 'BL', code: '391720'),
      ProductVariant(storage: '512GB', color: 'SL', code: '391721'),
      ProductVariant(storage: '512GB', color: 'OR', code: '391722'),
      ProductVariant(storage: '512GB', color: 'BL', code: '392557'),
    ],
  ),
  // --- SAMSUNG ---
  Product(
    id: 't12',
    name: 'Galaxy A15',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya15.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BL', code: '224703'),
    ],
  ),
  Product(
    id: 't13',
    name: 'Galaxy A15 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya155g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BB', code: '399118'),
    ],
  ),
  Product(
    id: 't14',
    name: 'A15 LTE (SMART)',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunga15ltesmart.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '368914'),
    ],
  ),
  Product(
    id: 't15',
    name: 'Galaxy A16',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya16.png',
    variants: [
      ProductVariant(storage: '4/128GB', color: 'GN', code: '408336'),
      ProductVariant(storage: '4/128GB', color: 'BK', code: '431292'),
    ],
  ),
  Product(
    id: 't16',
    name: 'Galaxy A16 LTE',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya16lte.png',
    variants: [
      ProductVariant(storage: '4/128GB', color: 'BK', code: '411110'),
      ProductVariant(storage: '4/128GB', color: 'GY', code: '411118'),
    ],
  ),
  Product(
    id: 't17',
    name: 'Galaxy A16 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya165g.png',
    variants: [
      ProductVariant(storage: '4/128GB', color: 'GN', code: '403374'),
    ],
  ),
  Product(
    id: 't18',
    name: 'Galaxy A17 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya175g.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '498241'),
      ProductVariant(storage: '128GB', color: 'BK', code: '498231'),
      ProductVariant(storage: '128GB', color: 'GY', code: '498237'),
      ProductVariant(storage: '128GB', color: 'BL', code: '498240'),
    ],
  ),
  Product(
    id: 't19',
    name: 'A17 4G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunga174g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '598620'),
    ],
  ),
  Product(
    id: 't20',
    name: 'Galaxy A26 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya265g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'WH', code: '425202'),
      ProductVariant(storage: '256GB', color: 'MI', code: '425201'),
    ],
  ),
  Product(
    id: 't21',
    name: 'Galaxy A27 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya275g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '586061'),
      ProductVariant(storage: '128GB', color: 'PK', code: '586072'),
      ProductVariant(storage: '128GB', color: 'BL', code: '586074'),
      ProductVariant(storage: '256GB', color: 'BK', code: '586071'),
    ],
  ),
  Product(
    id: 't22',
    name: 'Galaxy A36 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya365g.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '425191'),
    ],
  ),
  Product(
    id: 't23',
    name: 'Galaxy A56 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya565g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'OL', code: '425181'),
      ProductVariant(storage: '256GB', color: 'BK', code: '425177'),
      ProductVariant(storage: '256GB', color: 'OL', code: '425187'),
    ],
  ),
  Product(
    id: 't24',
    name: 'Galaxy A37 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya375g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'CH', code: '573351'),
      ProductVariant(storage: '128GB', color: 'GG', code: '573361'),
      ProductVariant(storage: '128GB', color: 'WH', code: '573369'),
      ProductVariant(storage: '256GB', color: 'CH', code: '573353'),
      ProductVariant(storage: '256GB', color: 'GG', code: '573363'),
      ProductVariant(storage: '256GB', color: 'WH', code: '573370'),
      ProductVariant(storage: '128GB', color: 'Lavanda', code: '573364'),
      ProductVariant(storage: '256GB', color: 'Lavanda', code: '573368'),
    ],
  ),
  Product(
    id: 't25',
    name: 'Galaxy A57 5G',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxya575g.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'NA', code: '573319'),
      ProductVariant(storage: '128GB', color: 'GY', code: '573321'),
      ProductVariant(storage: '128GB', color: 'BL', code: '573343'),
      ProductVariant(storage: '128GB', color: 'LI', code: '573348'),
      ProductVariant(storage: '256GB', color: 'NA', code: '573320'),
      ProductVariant(storage: '256GB', color: 'GY', code: '573323'),
      ProductVariant(storage: '256GB', color: 'BL', code: '573347'),
      ProductVariant(storage: '256GB', color: 'LI', code: '573349'),
    ],
  ),
  Product(
    id: 't26',
    name: 'Galaxy S25 FE',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys25fe.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '583946'),
      ProductVariant(storage: '256GB', color: 'Blu Navy', code: '583947'),
    ],
  ),
  Product(
    id: 't27',
    name: 'Galaxy S25+',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys25plus.png',
    variants: [
      ProductVariant(storage: '512GB', color: 'SV', code: '412437'),
      ProductVariant(storage: '512GB', color: 'NA', code: '412435'),
      ProductVariant(storage: '512GB', color: 'BB', code: '528526'),
      ProductVariant(storage: '256GB', color: 'SV', code: '412436'),
    ],
  ),
  Product(
    id: 't28',
    name: 'Galaxy S25 Edge',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys25edge.png',
    variants: [
      ProductVariant(storage: '512GB', color: 'BK', code: '429813'),
    ],
  ),
  Product(
    id: 't29',
    name: 'Galaxy S25',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys25.png',
    variants: [
      ProductVariant(storage: '512GB', color: 'NA', code: '412447'),
      ProductVariant(storage: '512GB', color: 'SV', code: '412451'),
      ProductVariant(storage: '256GB', color: 'BL', code: '412439'),
      ProductVariant(storage: '256GB', color: 'GN', code: '412442'),
      ProductVariant(storage: '256GB', color: 'NA', code: '412446'),
      ProductVariant(storage: '256GB', color: 'SV', code: '412449'),
      ProductVariant(storage: '256GB', color: 'BLBK', code: '527268'),
      ProductVariant(storage: '512GB', color: 'BB', code: '528524'),
    ],
  ),
  Product(
    id: 't30',
    name: 'Galaxy Z Flip7',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxyzflip7.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '498695'),
      ProductVariant(storage: '512GB', color: 'BK', code: '457074'),
    ],
  ),
  Product(
    id: 't31',
    name: 'Galaxy S25 Ultra',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys25ultra.png',
    variants: [
      ProductVariant(storage: '1TB', color: 'BK', code: '412327'),
      ProductVariant(storage: '256GB', color: 'WH', code: '412422'),
      ProductVariant(storage: '512GB', color: 'WH', code: '412423'),
      ProductVariant(storage: '256GB', color: 'BL', code: '412393'),
      ProductVariant(storage: '256GB', color: 'GY', code: '412412'),
      ProductVariant(storage: '1TB', color: 'GY', code: '412420'),
      ProductVariant(storage: '1TB', color: 'BL', code: '412411'),
    ],
  ),
  Product(
    id: 't32',
    name: 'Galaxy S26',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys26.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'WH', code: '564048'),
      ProductVariant(storage: '256GB', color: 'VI', code: '564051'),
      ProductVariant(storage: '256GB', color: 'BL', code: '564053'),
      ProductVariant(storage: '256GB', color: 'BK', code: '564055'),
      ProductVariant(storage: '512GB', color: 'WH', code: '564050'),
      ProductVariant(storage: '512GB', color: 'VI', code: '564052'),
      ProductVariant(storage: '512GB', color: 'BL', code: '564054'),
      ProductVariant(storage: '512GB', color: 'BK', code: '564057'),
    ],
  ),
  Product(
    id: 't33',
    name: 'Galaxy S25 Ultra (TIM)',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys25ultratim.png',
    variants: [
      ProductVariant(storage: '512GB', color: 'BK', code: '420370'),
      ProductVariant(storage: '512GB', color: 'SV', code: '420371'),
      ProductVariant(storage: '512GB', color: 'BL', code: '420374'),
    ],
  ),
  Product(
    id: 't34',
    name: 'Galaxy S26+',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys26plus.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'WH', code: '564040'),
      ProductVariant(storage: '256GB', color: 'VI', code: '564042'),
      ProductVariant(storage: '512GB', color: 'WH', code: '564041'),
      ProductVariant(storage: '512GB', color: 'BK', code: '564047'),
    ],
  ),
  Product(
    id: 't35',
    name: 'Galaxy Z Flip8',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxyzflip8.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'GR', code: '593090'),
      ProductVariant(storage: '256GB', color: 'PK', code: '593092'),
      ProductVariant(storage: '512GB', color: 'GR', code: '593091'),
      ProductVariant(storage: '256GB', color: 'Crema', code: '593088'),
      ProductVariant(storage: '512GB', color: 'Crema', code: '593089'),
      ProductVariant(storage: '512GB', color: 'Rosa', code: '593094'),
    ],
  ),
  Product(
    id: 't36',
    name: 'Galaxy S26 Ultra',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys26ultra.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'WH', code: '564017'),
      ProductVariant(storage: '256GB', color: 'VI', code: '564023'),
      ProductVariant(storage: '256GB', color: 'BL', code: '564027'),
      ProductVariant(storage: '256GB', color: 'BK', code: '564035'),
      ProductVariant(storage: '512GB', color: 'WH', code: '564018'),
      ProductVariant(storage: '512GB', color: 'VI', code: '564025'),
      ProductVariant(storage: '512GB', color: 'BL', code: '564033'),
      ProductVariant(storage: '512GB', color: 'BK', code: '564036'),
      ProductVariant(storage: '1TB', color: 'VI', code: '564026'),
      ProductVariant(storage: '1TB', color: 'BL', code: '564034'),
      ProductVariant(storage: '1TB', color: 'BK', code: '564038'),
    ],
  ),
  Product(
    id: 't37',
    name: 'Galaxy S26 Ultra 5G (SMART)',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxys26ultra5gsmart.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BL', code: '574851'),
    ],
  ),
  Product(
    id: 't38',
    name: 'Galaxy Z Fold7',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxyzfold7.png',
    variants: [
      ProductVariant(storage: '512GB', color: 'BK', code: '498694'),
      ProductVariant(storage: '1TB', color: 'Nero Intenso', code: '457060'),
    ],
  ),
  Product(
    id: 't39',
    name: 'Galaxy Z Fold8',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxyzfold8.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'GR', code: '593098'),
      ProductVariant(storage: '256GB', color: 'Crema', code: '593095'),
      ProductVariant(storage: '512GB', color: 'Crema', code: '593096'),
      ProductVariant(storage: '1TB', color: 'Crema', code: '593097'),
      ProductVariant(storage: '512GB', color: 'Grafite', code: '593099'),
      ProductVariant(storage: '1TB', color: 'Grafite', code: '593100'),
      ProductVariant(storage: '256GB', color: 'Lavanda', code: '593101'),
      ProductVariant(storage: '512GB', color: 'Lavanda', code: '593102'),
      ProductVariant(storage: '1TB', color: 'Lavanda', code: '593103'),
    ],
  ),
  Product(
    id: 't40',
    name: 'Galaxy Z Fold8 Ultra',
    brand: 'Samsung',
    category: 'Telefonia',
    imagePath: 'assets/products/samsunggalaxyzfold8ultra.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'GR', code: '593080'),
      ProductVariant(storage: '256GB', color: 'VI', code: '593084'),
      ProductVariant(storage: '512GB', color: 'VI', code: '593086'),
      ProductVariant(storage: '256GB', color: 'Crema', code: '593077'),
      ProductVariant(storage: '512GB', color: 'Crema', code: '593078'),
      ProductVariant(storage: '1TB', color: 'Crema', code: '593079'),
      ProductVariant(storage: '512GB', color: 'Grafite', code: '593081'),
      ProductVariant(storage: '1TB', color: 'Grafite', code: '593082'),
      ProductVariant(storage: '1TB', color: 'Ombra Viola', code: '593087'),
    ],
  ),
  // --- XIAOMI ---
  Product(
    id: 't41',
    name: 'Redmi A5 +Redmi Buds (TIM)',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredmia5redmibudstim.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'GO', code: '551618'),
    ],
  ),
  Product(
    id: 't42',
    name: 'Redmi A5',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredmia5.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'GN', code: '545563'),
    ],
  ),
  Product(
    id: 't43',
    name: 'Redmi Note 14',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote14.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BL', code: '415735'),
      ProductVariant(storage: '128GB', color: 'BK', code: '420304'),
      ProductVariant(storage: '128GB', color: 'GN', code: '420308'),
      ProductVariant(storage: 'Standard', color: 'BK', code: '415744'),
    ],
  ),
  Product(
    id: 't44',
    name: 'Redmi A7 Pro',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredmia7pro.png',
    variants: [
      ProductVariant(storage: '4+64GB', color: 'BK', code: '576413'),
      ProductVariant(storage: '4+64GB', color: 'BL', code: '576415'),
      ProductVariant(storage: '4+128GB', color: 'BK', code: '576519'),
      ProductVariant(storage: '4+128GB', color: 'BL', code: '576520'),
    ],
  ),
  Product(
    id: 't45',
    name: 'Redmi 15C',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredmi15c.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'GY', code: '467135'),
      ProductVariant(storage: '4+128GB', color: 'GN', code: '467136'),
      ProductVariant(storage: '4+256GB', color: 'GY', code: '467151'),
      ProductVariant(storage: '4+256GB', color: 'OR', code: '496008'),
    ],
  ),
  Product(
    id: 't46',
    name: 'Redmi 15',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredmi15.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'PU', code: '498229'),
    ],
  ),
  Product(
    id: 't47',
    name: 'Redmi Note 15',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote15.png',
    variants: [
      ProductVariant(storage: '6+128GB', color: 'BK', code: '563288'),
      ProductVariant(storage: '8+256GB', color: 'BK', code: '557247'),
    ],
  ),
  Product(
    id: 't48',
    name: 'Note 14 Pro 5G +Watch 5Lite',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaominote14pro5gwatch5lite.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '415467'),
    ],
  ),
  Product(
    id: 't49',
    name: 'Redmi Note 14 Pro',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote14pro.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'PU', code: '415753'),
      ProductVariant(storage: 'Standard', color: 'BK', code: '415759'),
    ],
  ),
  Product(
    id: 't50',
    name: 'Redmi Note 14 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote145g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '415745'),
    ],
  ),
  Product(
    id: 't51',
    name: 'Redmi Note 15 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote155g.png',
    variants: [
      ProductVariant(storage: '6+128GB', color: 'BL', code: '565493'),
      ProductVariant(storage: '8+256GB', color: 'BK', code: '557278'),
      ProductVariant(storage: '8+256GB', color: 'PU', code: '557285'),
      ProductVariant(storage: '8+256GB', color: 'BL', code: '557287'),
    ],
  ),
  Product(
    id: 't52',
    name: 'Redmi 17',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredmi17.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'BK', code: '595175'),
      ProductVariant(storage: '4+128GB', color: 'BL', code: '595184'),
      ProductVariant(storage: '4+128GB', color: 'GN', code: '595186'),
      ProductVariant(storage: '4+256GB', color: 'BK', code: '595189'),
      ProductVariant(storage: '4+256GB', color: 'BL', code: '595190'),
      ProductVariant(storage: '4+256GB', color: 'GN', code: '595192'),
    ],
  ),
  Product(
    id: 't53',
    name: 'Redmi Note 14 Pro 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote14pro5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '419653'),
      ProductVariant(storage: 'Standard', color: 'PU', code: '415769'),
    ],
  ),
  Product(
    id: 't54',
    name: 'Redmi Note 15 Pro',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote15pro.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '557260'),
    ],
  ),
  Product(
    id: 't55',
    name: 'Note 14 Pro+ + Watch 5Lite',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaominote14prowatch5lite.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '415195'),
    ],
  ),
  Product(
    id: 't56',
    name: 'Redmi Note 14 Pro+ 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote14proplus5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'PU', code: '415779'),
    ],
  ),
  Product(
    id: 't57',
    name: 'Redmi Note 15 Pro 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote15pro5g.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '557269'),
      ProductVariant(storage: '8+512GB', color: 'BK', code: '563254'),
    ],
  ),
  Product(
    id: 't58',
    name: 'Redmi Note 17 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote175g.png',
    variants: [
      ProductVariant(storage: '6+256GB', color: 'BK', code: '598133'),
    ],
  ),
  Product(
    id: 't59',
    name: 'Redmi Note 15 Pro+ 5G',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomiredminote15proplus5g.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BL', code: '557270'),
      ProductVariant(storage: '8+256GB', color: 'BK', code: '557274'),
    ],
  ),
  Product(
    id: 't60',
    name: 'Xiaomi 15',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomixiaomi15.png',
    variants: [
      ProductVariant(storage: '12+256GB', color: 'BK', code: '423226'),
      ProductVariant(storage: '12+256GB', color: 'WH', code: '423232'),
      ProductVariant(storage: '12+512GB', color: 'GN', code: '423237'),
    ],
  ),
  Product(
    id: 't61',
    name: 'Xiaomi 17T',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomixiaomi17t.png',
    variants: [
      ProductVariant(storage: '12+256GB', color: 'BK', code: '582785'),
      ProductVariant(storage: '12+256GB', color: 'BL', code: '582786'),
      ProductVariant(storage: '12+256GB', color: 'VI', code: '582787'),
      ProductVariant(storage: '12+512GB', color: 'BL', code: '582788'),
      ProductVariant(storage: '12+512GB', color: 'BK', code: '582797'),
      ProductVariant(storage: '12+512GB', color: 'VI', code: '582799'),
    ],
  ),
  Product(
    id: 't62',
    name: 'Xiaomi 17T Pro',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomixiaomi17tpro.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'VI', code: '582757'),
      ProductVariant(storage: '12+512GB', color: 'BK', code: '582767'),
    ],
  ),
  Product(
    id: 't63',
    name: 'Xiaomi 17',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomixiaomi17.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'BK', code: '565448'),
      ProductVariant(storage: '12+512GB', color: 'BL', code: '565472'),
      ProductVariant(storage: '12+512GB', color: 'GN', code: '565473'),
    ],
  ),
  Product(
    id: 't64',
    name: 'Xiaomi 17 Ultra',
    brand: 'Xiaomi',
    category: 'Telefonia',
    imagePath: 'assets/products/xiaomixiaomi17ultra.png',
    variants: [
      ProductVariant(storage: '16+512GB', color: 'BK', code: '565475'),
      ProductVariant(storage: '16+512GB', color: 'GN', code: '565476'),
    ],
  ),
  // --- ZTE ---
  Product(
    id: 't65',
    name: 'Blade A36',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztebladea36.png',
    variants: [
      ProductVariant(storage: '4+64GB', color: 'BK', code: '583221'),
      ProductVariant(storage: '4+128GB', color: 'BK', code: '573903'),
      ProductVariant(storage: '4+128GB', color: 'GN', code: '573918'),
    ],
  ),
  Product(
    id: 't66',
    name: 'Blade V70 Vita',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztebladev70vita.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GY', code: '425010'),
      ProductVariant(storage: '8+256GB', color: 'GN', code: '425051'),
    ],
  ),
  Product(
    id: 't67',
    name: 'Blade A75 5G',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztebladea755g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'B', code: '409779'),
    ],
  ),
  Product(
    id: 't68',
    name: 'Blade A76 5G',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztebladea765g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '462856'),
    ],
  ),
  Product(
    id: 't69',
    name: 'V80 Vita',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztev80vita.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '576460'),
      ProductVariant(storage: 'Standard', color: 'CY', code: '576463'),
    ],
  ),
  Product(
    id: 't70',
    name: 'Nubia Neo 3 5G',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztenubianeo35g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '433013'),
      ProductVariant(storage: 'Standard', color: 'SV', code: '433015'),
    ],
  ),
  Product(
    id: 't71',
    name: 'V80 Max',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztev80max.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '576465'),
      ProductVariant(storage: 'Standard', color: 'SV', code: '576473'),
    ],
  ),
  Product(
    id: 't72',
    name: 'V80 Pro',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztev80pro.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '575056'),
    ],
  ),
  Product(
    id: 't73',
    name: 'Nubia Neo 3 GT 5G',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztenubianeo3gt5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'GY', code: '433017'),
    ],
  ),
  Product(
    id: 't74',
    name: 'Nubia Air',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztenubiaair.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '530222'),
      ProductVariant(storage: 'Standard', color: 'TBK', code: '558251'),
    ],
  ),
  Product(
    id: 't75',
    name: 'Nubia Neo 5 GT 5G',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztenubianeo5gt5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '582706'),
    ],
  ),
  Product(
    id: 't76',
    name: 'Nubia Air Pro',
    brand: 'ZTE',
    category: 'Telefonia',
    imagePath: 'assets/products/ztenubiaairpro.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '577858'),
    ],
  ),
  // --- REALME ---
  Product(
    id: 't77',
    name: 'Note 70T',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmenote70t.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'BK', code: '535837'),
    ],
  ),
  Product(
    id: 't78',
    name: 'C71',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmec71.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GN', code: '455007'),
    ],
  ),
  Product(
    id: 't79',
    name: 'C75',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmec75.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'GO', code: '417832'),
    ],
  ),
  Product(
    id: 't80',
    name: 'C100 5G',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmec1005g.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'GN', code: '582759'),
      ProductVariant(storage: '4+256GB', color: 'GN', code: '582768'),
    ],
  ),
  Product(
    id: 't81',
    name: 'Realme 14 5G',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmerealme145g.png',
    variants: [
      ProductVariant(storage: '12+256GB', color: 'TG', code: '432063'),
    ],
  ),
  Product(
    id: 't82',
    name: 'GT 7T 5G',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmegt7t5g.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'BL', code: '446439'),
      ProductVariant(storage: '12+512GB', color: 'YE', code: '446430'),
    ],
  ),
  Product(
    id: 't83',
    name: 'Realme 16 Pro 5G',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmerealme16pro5g.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GY', code: '566044'),
      ProductVariant(storage: '8+512GB', color: 'GY', code: '566001'),
      ProductVariant(storage: '8+512GB', color: 'PU', code: '566017'),
    ],
  ),
  Product(
    id: 't84',
    name: 'Realme 14 Pro+ 5G',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmerealme14pro5g.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'GY', code: '423064'),
    ],
  ),
  Product(
    id: 't85',
    name: 'GT 7 5G + Watch S2',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmegt75gwatchs2.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'BK', code: '446253'),
    ],
  ),
  Product(
    id: 't86',
    name: 'Realme 16 Pro+ 5G',
    brand: 'Realme',
    category: 'Telefonia',
    imagePath: 'assets/products/realmerealme16proplus5g.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'GY', code: '566082'),
    ],
  ),
  // --- OPPO ---
  Product(
    id: 't87',
    name: 'A6x',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppoa6x.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'PURPLE', code: '561530'),
    ],
  ),
  Product(
    id: 't88',
    name: 'Reno 12F 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno12f5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '381815'),
    ],
  ),
  Product(
    id: 't89',
    name: 'A6k',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppoa6k.png',
    variants: [
      ProductVariant(storage: '4+256GB', color: 'CRYSTAL BK', code: '561868'),
    ],
  ),
  Product(
    id: 't90',
    name: 'A6',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppoa6.png',
    variants: [
      ProductVariant(storage: '6+256GB', color: 'SAPPHIRE BK', code: '561869'),
      ProductVariant(storage: '6+256GB', color: 'AURORA GOLD', code: '561880'),
    ],
  ),
  Product(
    id: 't91',
    name: 'A6 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppoa65g.png',
    variants: [
      ProductVariant(storage: '6+256GB', color: 'SAPPHIRE BK', code: '561882'),
      ProductVariant(storage: '6+256GB', color: 'AURORA GOLD', code: '561884'),
    ],
  ),
  Product(
    id: 't92',
    name: 'A6 Pro 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppoa6pro5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '529454'),
      ProductVariant(storage: 'Standard', color: 'WH', code: '530109'),
    ],
  ),
  Product(
    id: 't93',
    name: 'A6 Pro 5G (SMART)',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppoa6pro5gsmart.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'SV', code: '554088'),
    ],
  ),
  Product(
    id: 't94',
    name: 'Reno15 F 5G + Buds3',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno15f5gbuds3.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '559839'),
    ],
  ),
  Product(
    id: 't95',
    name: 'Reno15 F 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno15f5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '564914'),
      ProductVariant(storage: 'Standard', color: 'BL', code: '564916'),
    ],
  ),
  Product(
    id: 't96',
    name: 'Reno15 FS 5G + Buds3',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno15fs5gbuds3.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '559844'),
    ],
  ),
  Product(
    id: 't97',
    name: 'Reno15 FS 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno15fs5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '564919'),
      ProductVariant(storage: 'Standard', color: 'BL', code: '564920'),
    ],
  ),
  Product(
    id: 't98',
    name: 'Reno15 5G + Buds3',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno155gbuds3.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'WH', code: '559837'),
    ],
  ),
  Product(
    id: 't99',
    name: 'Reno15 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno155g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '564896'),
      ProductVariant(storage: 'Standard', color: 'WH', code: '564912'),
    ],
  ),
  Product(
    id: 't100',
    name: 'Reno16 FS 5G - Bundle',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno16fs5gbundle.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'PUR', code: '588834'),
    ],
  ),
  Product(
    id: 't101',
    name: 'Reno15 Pro 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno15pro5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BL', code: '564892'),
      ProductVariant(storage: 'Standard', color: 'BK', code: '564894'),
    ],
  ),
  Product(
    id: 't102',
    name: 'Reno16 F 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno16f5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '597298'),
      ProductVariant(storage: 'Standard', color: 'WH', code: '597332'),
    ],
  ),
  Product(
    id: 't103',
    name: 'Reno16 5G - Bundle',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno165gbundle.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'WHT', code: '588747'),
      ProductVariant(storage: 'Standard', color: 'PUR', code: '588833'),
    ],
  ),
  Product(
    id: 't104',
    name: 'Reno16 Pro 5G - Bundle',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/opporeno16pro5gbundle.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'WHT', code: '588743'),
      ProductVariant(storage: 'Standard', color: 'STBK', code: '588831'),
    ],
  ),
  Product(
    id: 't105',
    name: 'Find X9 Pro 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppofindx9pro5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'SV', code: '548102'),
      ProductVariant(storage: 'Standard', color: 'WH', code: '548112'),
    ],
  ),
  Product(
    id: 't106',
    name: 'Find X9 Ultra 5G Box',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppofindx9ultra5gbox.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BR', code: '580374'),
    ],
  ),
  Product(
    id: 't107',
    name: 'Find X9 Ultra 5G',
    brand: 'Oppo',
    category: 'Telefonia',
    imagePath: 'assets/products/oppofindx9ultra5g.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BR', code: '580383'),
      ProductVariant(storage: 'Standard', color: 'OR', code: '580384'),
    ],
  ),
  // --- GOOGLE ---
  Product(
    id: 't108',
    name: 'Pixel 10a',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel10a.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '565937'),
      ProductVariant(storage: '256GB', color: 'BK', code: '565983'),
      ProductVariant(storage: '256GB', color: 'GY', code: '565990'),
    ],
  ),
  Product(
    id: 't109',
    name: 'Pixel 10',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel10.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'PU', code: '498189'),
      ProductVariant(storage: '128GB', color: 'BL', code: '498197'),
      ProductVariant(storage: '128GB', color: 'BK', code: '498198'),
      ProductVariant(storage: '256GB', color: 'GN', code: '498200'),
      ProductVariant(storage: '256GB', color: 'BK', code: '498203'),
      ProductVariant(storage: '256GB', color: 'Blu Indaco', code: '498201'),
    ],
  ),
  Product(
    id: 't110',
    name: 'Pixel 10 Pro',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel10pro.png',
    variants: [
      ProductVariant(storage: '512GB', color: 'GY', code: '498213'),
    ],
  ),
  Product(
    id: 't111',
    name: 'Pixel 10 Pro XL',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel10proxl.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'SV', code: '498219'),
      ProductVariant(storage: '512GB', color: 'BK', code: '498223'),
    ],
  ),
  Product(
    id: 't112',
    name: 'Pixel 11',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel11.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '596605'),
      ProductVariant(storage: '256GB', color: 'VI', code: '596676'),
      ProductVariant(storage: '256GB', color: 'GN', code: '596683'),
      ProductVariant(storage: '512GB', color: 'BK', code: '596699'),
      ProductVariant(storage: '512GB', color: 'VI', code: '596703'),
      ProductVariant(storage: '256GB', color: 'Rosa Ibisco', code: '596698'),
    ],
  ),
  Product(
    id: 't113',
    name: 'Pixel 11 Pro',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel11pro.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '596708'),
      ProductVariant(storage: '256GB', color: 'GY', code: '596725'),
      ProductVariant(storage: '256GB', color: 'PK', code: '596730'),
      ProductVariant(storage: '512GB', color: 'BK', code: '596731'),
      ProductVariant(storage: '256GB', color: 'Verde Oliva', code: '596729'),
      ProductVariant(storage: '512GB', color: 'Grigio Nebbia', code: '596732'),
      ProductVariant(storage: '512GB', color: 'Verde Oliva', code: '596733'),
    ],
  ),
  Product(
    id: 't114',
    name: 'Pixel 11 Pro XL',
    brand: 'Google',
    category: 'Telefonia',
    imagePath: 'assets/products/googlepixel11proxl.png',
    variants: [
      ProductVariant(storage: '256GB', color: 'BK', code: '596807'),
      ProductVariant(storage: '256GB', color: 'GY', code: '596845'),
      ProductVariant(storage: '512GB', color: 'BK', code: '596877'),
      ProductVariant(storage: '256GB', color: 'Verde Oliva', code: '596857'),
      ProductVariant(storage: '512GB', color: 'Verde Oliva', code: '596896'),
    ],
  ),
  // --- HONOR ---
  Product(
    id: 't115',
    name: 'X5c Plus',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorx5cplus.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'BK', code: '530378'),
      ProductVariant(storage: '4+256GB', color: 'CY', code: '530367'),
    ],
  ),
  Product(
    id: 't116',
    name: 'X5c Plus (TIM)',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorx5cplustim.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'BK', code: '556863'),
      ProductVariant(storage: 'Standard', color: 'BK', code: '596000'),
    ],
  ),
  Product(
    id: 't117',
    name: 'Honor 400 Smart',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor400smart.png',
    variants: [
      ProductVariant(storage: '6+128GB', color: 'BK', code: '521209'),
      ProductVariant(storage: '8+256GB', color: 'BK', code: '592000'),
      ProductVariant(storage: '8+256GB', color: 'GO', code: '592001'),
    ],
  ),
  Product(
    id: 't118',
    name: 'Honor 400 Smart + cover + Choice X7 Lite',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor400smartcoverchoicex7lite.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GO', code: '521216'),
    ],
  ),
  Product(
    id: 't119',
    name: 'Honor 400 Lite (SMART)',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor400litesmart.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '434813'),
    ],
  ),
  Product(
    id: 't120',
    name: 'Honor 600 Smart (SMART)',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor600smartsmart.png',
    variants: [
      ProductVariant(storage: '128GB', color: 'BK', code: '593444'),
    ],
  ),
  Product(
    id: 't121',
    name: 'Honor 600 Smart',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor600smart.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'BK', code: '590563'),
      ProductVariant(storage: '4+128GB', color: 'SV', code: '590565'),
      ProductVariant(storage: '4+256GB', color: 'BK', code: '590573'),
      ProductVariant(storage: '4+256GB', color: 'SV', code: '590575'),
    ],
  ),
  Product(
    id: 't122',
    name: 'Honor 400 Lite',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor400lite.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GY', code: '427325'),
    ],
  ),
  Product(
    id: 't123',
    name: 'Magic8 Lite 256 Bundle',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honormagic8lite256bundle.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'GN', code: '559754'),
    ],
  ),
  Product(
    id: 't124',
    name: 'Honor 600 Lite 256 + Watch 2i',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor600lite256watch2i.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '574056'),
      ProductVariant(storage: 'Standard', color: 'GY', code: '574062'),
      ProductVariant(storage: 'Standard', color: 'GN', code: '574064'),
    ],
  ),
  Product(
    id: 't125',
    name: 'Magic8 Lite 512 Bundle',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honormagic8lite512bundle.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '559758'),
      ProductVariant(storage: 'Standard', color: 'GN', code: '559759'),
    ],
  ),
  Product(
    id: 't126',
    name: 'Honor 400 + Choice Clip New',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor400choiceclipnew.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'BK', code: '559981'),
      ProductVariant(storage: 'Standard', color: 'SV', code: '559982'),
      ProductVariant(storage: 'Standard', color: 'GO', code: '559983'),
    ],
  ),
  Product(
    id: 't127',
    name: 'Honor 600 + Watch 2i',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor600watch2i.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '578659'),
      ProductVariant(storage: '8+256GB', color: 'GO', code: '578661'),
      ProductVariant(storage: '8+256GB', color: 'OR', code: '578662'),
      ProductVariant(storage: '8+512GB', color: 'BK', code: '578668'),
      ProductVariant(storage: '8+512GB', color: 'GO', code: '578669'),
      ProductVariant(storage: '8+512GB', color: 'OR', code: '578671'),
    ],
  ),
  Product(
    id: 't128',
    name: 'Honor 600 Pro',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honorhonor600pro.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'BK', code: '578677'),
      ProductVariant(storage: '12+512GB', color: 'GO', code: '578680'),
    ],
  ),
  Product(
    id: 't129',
    name: 'Magic V6',
    brand: 'Honor',
    category: 'Telefonia',
    imagePath: 'assets/products/honormagicv6.png',
    variants: [
      ProductVariant(storage: '16+512GB', color: 'BK', code: '589408'),
    ],
  ),
  // --- MOTOROLA ---
  Product(
    id: 't130',
    name: 'Moto E15 4G',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotoe154g.png',
    variants: [
      ProductVariant(storage: '2+64GB', color: 'LA', code: '434811'),
    ],
  ),
  Product(
    id: 't131',
    name: 'Moto G05',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog05.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'GN', code: '435052'),
      ProductVariant(storage: '4+256GB', color: 'RD', code: '527885'),
      ProductVariant(storage: '4+256GB', color: 'GN', code: '425245'),
      ProductVariant(storage: '8+256GB', color: 'BL', code: '531133'),
      ProductVariant(storage: '8+256GB', color: 'GN', code: '531134'),
    ],
  ),
  Product(
    id: 't132',
    name: 'Moto G06',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog06.png',
    variants: [
      ProductVariant(storage: '4+128GB', color: 'BL', code: '553357'),
      ProductVariant(storage: '4+128GB', color: 'GN', code: '553364'),
      ProductVariant(storage: '4+256GB', color: 'BL', code: '553366'),
      ProductVariant(storage: '4+256GB', color: 'GN', code: '553369'),
    ],
  ),
  Product(
    id: 't133',
    name: 'Moto G56 5G',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog565g.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '434965'),
      ProductVariant(storage: '8+512GB', color: 'GY', code: '583135'),
    ],
  ),
  Product(
    id: 't134',
    name: 'Thinkphone 25',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolathinkphone25.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '420146'),
    ],
  ),
  Product(
    id: 't135',
    name: 'Moto G15',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog15.png',
    variants: [
      ProductVariant(storage: '8+512GB', color: 'BL', code: '423950'),
      ProductVariant(storage: '8+512GB', color: 'GY', code: '425248'),
      ProductVariant(storage: '8+512GB', color: 'GN', code: '425254'),
    ],
  ),
  Product(
    id: 't136',
    name: 'G15 Power',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolag15power.png',
    variants: [
      ProductVariant(storage: '8+512GB', color: 'GY', code: '531135'),
      ProductVariant(storage: '8+512GB', color: 'GN', code: '531136'),
    ],
  ),
  Product(
    id: 't137',
    name: 'Edge 60 Fusion',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolaedge60fusion.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GY', code: '454981'),
    ],
  ),
  Product(
    id: 't138',
    name: 'Moto g57',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog57.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GN', code: '564371'),
      ProductVariant(storage: '8+256GB', color: 'BL', code: '564385'),
    ],
  ),
  Product(
    id: 't139',
    name: 'Moto G86 5G (TIM)',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog865gtim.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'SV', code: '554536'),
      ProductVariant(storage: '8+256GB', color: 'GO', code: '554538'),
    ],
  ),
  Product(
    id: 't140',
    name: 'Moto g77',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog77.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '564386'),
      ProductVariant(storage: '8+256GB', color: 'BL', code: '564387'),
    ],
  ),
  Product(
    id: 't141',
    name: 'Moto G87',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolamotog87.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'BK', code: '583298'),
    ],
  ),
  Product(
    id: 't142',
    name: 'Edge 60 Pro',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolaedge60pro.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'GN', code: '430362'),
      ProductVariant(storage: '12+512GB', color: 'PU', code: '430364'),
      ProductVariant(storage: '12+512GB', color: 'SH', code: '562228'),
      ProductVariant(storage: '12+512GB', color: 'WA', code: '562333'),
    ],
  ),
  Product(
    id: 't143',
    name: 'Razr 50 Ultra',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolarazr50ultra.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'BL', code: '369523'),
    ],
  ),
  Product(
    id: 't144',
    name: 'Edge 70 (TIM)',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolaedge70tim.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'GY', code: '551614'),
      ProductVariant(storage: 'Standard', color: 'GN', code: '551615'),
    ],
  ),
  Product(
    id: 't145',
    name: 'Razr 60 Ultra',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolarazr60ultra.png',
    variants: [
      ProductVariant(storage: 'Standard', color: 'GN', code: '425620'),
    ],
  ),
  Product(
    id: 't146',
    name: 'Signature',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolasignature.png',
    variants: [
      ProductVariant(storage: '16+512GB', color: 'BK', code: '564674'),
    ],
  ),
  Product(
    id: 't147',
    name: 'Razr 70',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolarazr70.png',
    variants: [
      ProductVariant(storage: '8+256GB', color: 'GN', code: '581409'),
    ],
  ),
  Product(
    id: 't148',
    name: 'Razr 70 plus',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolarazr70plus.png',
    variants: [
      ProductVariant(storage: '12+512GB', color: 'GN', code: '582408'),
    ],
  ),
  Product(
    id: 't149',
    name: 'Razr Fold',
    brand: 'Motorola',
    category: 'Telefonia',
    imagePath: 'assets/products/motorolarazrfold.png',
    variants: [
      ProductVariant(storage: '16+512GB', color: 'WH', code: '583136'),
      ProductVariant(storage: '16+512GB', color: 'BK', code: '583137'),
    ],
  ),
];
